//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string OwnerId { get; set; }
        public bool CheckedOut { get; set; }
        public int LocationId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UserUpdate { get; set; }
        public string DeviceName { get; set; }
        public System.DateTime DateDeployed { get; set; }
        public System.DateTime DateReturned { get; set; }
        public string Bitlocker { get; set; }
    }
}
