//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int Id { get; set; }
        public string OwnerName { get; set; }
        public string UserName { get; set; }
        public int DepartmentId { get; set; }
        public bool OwnerStatus { get; set; }
    }
}
