//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeopleEntities1 : DbContext
    {
        public PeopleEntities1()
            : base("name=PeopleEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<ComputerBrand> ComputerBrands { get; set; }
        public virtual DbSet<ComputerModel> ComputerModels { get; set; }
    }
}
